name: Deploy infrastructure

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: Apply Terraform Infra
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout/@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::146624863487:role/GitHub-Actions
          aws-region: us-east-1

      - name: Run Terraform init
        run: make init

      - name: Run Terraform plan
        run: make plan
      
      - name: Run Terraform apply
        run: make apply
