name: Destroy Terraform Backend

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: Charly-Wolf/my-github-actions/.github/actions/setup-aws@main

      - name: Give execute permission to destroy script
        run: chmod +x .github/scripts/destroy-terraform-backend.sh

      - name: Run destroy backend script
        run: ./.github/scripts/destroy-terraform-backend.sh
