name: Destroy infra

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: Destroy Terraform Infra
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout/@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.2

      - name: Configure AWS Credentials from OIDC
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::146624863487:role/GitHub-Actions
          aws-region: us-east-1

      - name: Run Terraform init
        run: make init

      - name: Run Terraform destroy
        run: make destroy
