name: Setup Terraform Backend

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: us-east-1

      - name: Give execute permission to script
        run: chmod +x ./.github/scripts/setup-terraform-backend.sh

      - name: Run backend setup script
        run: ./.github/scripts/setup-terraform-backend.sh
